### ISSUE TITLE
The edit product page crash after I select a product for synchronization 

### ISSUE THREAD

**Issue by gendrith** [woocommerce/facebook-for-woocommerce#2225]
Just like the title says, if I mark a product for sync in the admin, the page crash after I update the product and this error shows.

Fatal error:  Uncaught Error: Call to a member function get_type() on bool in wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php:20
Stack trace:
```
#0 wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(33): include()
#1 wp-admin/includes/template.php(1401): WC_Meta_Box_Product_Data::output(Object(WP_Post), Array)
#2 wp-admin/edit-form-advanced.php(688): do_meta_boxes(Object(WP_Screen), 'normal', Object(WP_Post))
#3 wp-admin/post.php(206): require('/var/www/vhosts...')
#4 {main}
  thrown in wp-content/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-panel.php on line 20
```

But, if the facebook sync is deactivated on a product, everything works perfectly on the Product Data box.

PS: this is the first time I post an issue (ever), I apologize in advance for any error

**Comment by rawdreeg** [comment]
Hi @gendrith 

Does this happen with all products or a specific one?

PS: Could you provide a screen recording of the steps to reproduce the issue and a copy of your [WC system status report](https://docs.woocommerce.com/document/understanding-the-woocommerce-system-status-report/)?

**Comment by gendrith** [comment]
Yes it happens with every active product, like I said before, after I mark it for syncronization and update the product the error shows up and prevent me to keep editing the product. 

![Captura de pantalla 2022-06-02 183040](https://user-images.githubusercontent.com/8031141/171749137-71f1b442-700b-48d7-b0df-08ba5c712eb5.png)


```
`
### WordPress Environment ###

WC Version: 6.5.1
REST API Version: ✔ 6.5.1
WC Blocks Version: ✔ 7.4.3
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.0
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 7.3.33
PHP Post Max Size: 8 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
cURL Version: 7.29.0
NSS/3.53.1

SUHOSIN Installed: –
MySQL Version: 5.5.68-MariaDB
Max Upload Size: 8 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 6.5.1
WC Database Prefix: wp0q_
Tamaño total de la base de datos: 279.31MB
Tamaño de los datos de la base de datos: 193.12MB
Tamaño del índice de la base de datos: 86.19MB
wp0q_woocommerce_sessions: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
wp0q_woocommerce_api_keys: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_woocommerce_attribute_taxonomies: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_woocommerce_downloadable_product_permissions: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp0q_woocommerce_order_items: Datos: 0.45MB + Índice: 0.17MB + Motor InnoDB
wp0q_woocommerce_order_itemmeta: Datos: 7.52MB + Índice: 3.91MB + Motor InnoDB
wp0q_woocommerce_tax_rates: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp0q_woocommerce_tax_rate_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_woocommerce_shipping_zones: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_woocommerce_shipping_zone_locations: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_woocommerce_shipping_zone_methods: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_woocommerce_payment_tokens: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_woocommerce_payment_tokenmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_woocommerce_log: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_actionscheduler_actions: Datos: 5.02MB + Índice: 2.75MB + Motor InnoDB
wp0q_actionscheduler_claims: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_actionscheduler_groups: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_actionscheduler_logs: Datos: 2.02MB + Índice: 2.03MB + Motor InnoDB
wp0q_ac_abandoned_cart_history_lite: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp0q_ac_email_templates_lite: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_ac_guest_abandoned_cart_history_lite: Datos: 0.05MB + Índice: 0.00MB + Motor InnoDB
wp0q_ac_sent_history_lite: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_aws_cache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_aws_index: Datos: 8.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_commentmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_comments: Datos: 2.52MB + Índice: 1.47MB + Motor InnoDB
wp0q_envialia_shipping: Datos: 0.31MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_content_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_core_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_flags: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_languages: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_icl_languages_translations: Datos: 0.19MB + Índice: 0.11MB + Motor InnoDB
wp0q_icl_locale_map: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_message_status: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_icl_mo_files_domains: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_node: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_reminders: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_strings: Datos: 8.52MB + Índice: 13.95MB + Motor InnoDB
wp0q_icl_string_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_string_packages: Datos: 0.09MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_string_pages: Datos: 13.52MB + Índice: 20.03MB + Motor InnoDB
wp0q_icl_string_positions: Datos: 0.06MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_string_status: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_string_translations: Datos: 6.52MB + Índice: 4.03MB + Motor InnoDB
wp0q_icl_string_urls: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_translate: Datos: 3.50MB + Índice: 0.14MB + Motor InnoDB
wp0q_icl_translate_job: Datos: 0.05MB + Índice: 0.02MB + Motor InnoDB
wp0q_icl_translations: Datos: 1.52MB + Índice: 1.28MB + Motor InnoDB
wp0q_icl_translation_batches: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_translation_downloads: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_icl_translation_status: Datos: 3.44MB + Índice: 0.13MB + Motor InnoDB
wp0q_links: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_options: Datos: 6.09MB + Índice: 0.16MB + Motor InnoDB
wp0q_packlink_entity: Datos: 19.48MB + Índice: 0.00MB + Motor InnoDB
wp0q_pmxe_exports: Datos: 1.47MB + Índice: 0.00MB + Motor InnoDB
wp0q_pmxe_google_cats: Datos: 0.39MB + Índice: 0.00MB + Motor InnoDB
wp0q_pmxe_posts: Datos: 1.52MB + Índice: 0.00MB + Motor InnoDB
wp0q_pmxe_templates: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
wp0q_postmeta: Datos: 50.16MB + Índice: 20.16MB + Motor InnoDB
wp0q_posts: Datos: 17.48MB + Índice: 3.67MB + Motor InnoDB
wp0q_revslider_css: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_css_bkp: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_layer_animations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_revslider_layer_animations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_revslider_navigations: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_revslider_navigations_bkp: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_revslider_sliders: Datos: 0.25MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_sliders_bkp: Datos: 0.34MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_slides: Datos: 0.13MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_slides_bkp: Datos: 0.20MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_static_slides: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_revslider_static_slides_bkp: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_sbi_feeds: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_sbi_feed_caches: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_sbi_instagram_feeds_posts: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_sbi_instagram_feed_locator: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_sbi_instagram_posts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_sbi_sources: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_tcb_api_error_log: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_termmeta: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_terms: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_term_relationships: Datos: 0.17MB + Índice: 0.11MB + Motor InnoDB
wp0q_term_taxonomy: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_tve_leads_contacts: Datos: 0.13MB + Índice: 0.00MB + Motor InnoDB
wp0q_tve_leads_contact_download: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_tve_leads_event_log: Datos: 1.52MB + Índice: 0.81MB + Motor InnoDB
wp0q_tve_leads_form_variations: Datos: 0.14MB + Índice: 0.06MB + Motor InnoDB
wp0q_tve_leads_group_options: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_tve_leads_saved_group_options: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_tve_leads_split_test: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_tve_leads_split_test_items: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_usermeta: Datos: 3.52MB + Índice: 3.81MB + Motor InnoDB
wp0q_users: Datos: 0.13MB + Índice: 0.14MB + Motor InnoDB
wp0q_wc_admin_notes: Datos: 0.08MB + Índice: 0.00MB + Motor InnoDB
wp0q_wc_admin_note_actions: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wc_category_lookup: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wc_customer_lookup: Datos: 0.19MB + Índice: 0.14MB + Motor InnoDB
wp0q_wc_download_log: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_wc_order_coupon_lookup: Datos: 0.06MB + Índice: 0.06MB + Motor InnoDB
wp0q_wc_order_product_lookup: Datos: 0.31MB + Índice: 0.30MB + Motor InnoDB
wp0q_wc_order_stats: Datos: 0.25MB + Índice: 0.22MB + Motor InnoDB
wp0q_wc_order_tax_lookup: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_wc_product_attributes_lookup: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wc_product_download_directories: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wc_product_meta_lookup: Datos: 0.11MB + Índice: 0.20MB + Motor InnoDB
wp0q_wc_rate_limits: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wc_reserved_stock: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wc_tax_rate_classes: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wc_webhooks: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wdr_order_discounts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wdr_order_item_discounts: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wdr_rules: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfBlockedIPLog: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfBlocks7: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp0q_wfConfig: Datos: 2.25MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfCrawlers: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfFileChanges: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfFileMods: Datos: 5.52MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfHits: Datos: 1.02MB + Índice: 0.16MB + Motor InnoDB
wp0q_wfHoover: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wfIssues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp0q_wfKnownFileList: Datos: 2.52MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfLiveTrafficHuman: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wfLocs: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfLogins: Datos: 0.19MB + Índice: 0.06MB + Motor InnoDB
wp0q_wfls_2fa_secrets: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_wfls_settings: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfNotifications: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfPendingIssues: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp0q_wfReverseCache: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wfSNIPCache: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp0q_wfStatus: Datos: 0.14MB + Índice: 0.09MB + Motor InnoDB
wp0q_wfTrafficRates: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wpmailsmtp_debug_events: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_wpmailsmtp_tasks_meta: Datos: 0.06MB + Índice: 0.00MB + Motor InnoDB
wp0q_wpr_rucss_resources: Datos: 0.02MB + Índice: 0.06MB + Motor InnoDB
wp0q_wpr_rucss_used_css: Datos: 0.02MB + Índice: 0.05MB + Motor InnoDB
wp0q_yith_wapo_groups: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_yith_wapo_types: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_yith_wccl_meta: Datos: 0.02MB + Índice: 0.00MB + Motor InnoDB
wp0q_yoast_indexable: Datos: 7.52MB + Índice: 3.27MB + Motor InnoDB
wp0q_yoast_indexable_hierarchy: Datos: 0.34MB + Índice: 0.47MB + Motor InnoDB
wp0q_yoast_migrations: Datos: 0.02MB + Índice: 0.02MB + Motor InnoDB
wp0q_yoast_primary_term: Datos: 0.02MB + Índice: 0.03MB + Motor InnoDB
wp0q_yoast_seo_links: Datos: 2.11MB + Índice: 0.67MB + Motor InnoDB
wp0q_yoast_seo_meta: Datos: 0.20MB + Índice: 0.00MB + Motor InnoDB

### Post Type Counts ###

acf: 1
acf-field: 12
acf-field-group: 2
attachment: 6627
csp_rules: 2
flamingo_contact: 1661
flamingo_inbound: 1901
mc4wp-form: 2
nav_menu_item: 23
oembed_cache: 416
page: 71
post: 67
product: 180
revision: 1980
shop_coupon: 18
shop_order: 2177
shop_order_refund: 31
templatera: 17
tve_form_type: 7
tve_lead_group: 7
tve_lead_shortcode: 4
vc_grid_item: 1
vc_settings_preset: 3
woo_discount: 1
wpcf7_contact_form: 4
yith_popup: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Los mensajes de error no deberían mostrarse a los visitantes.

### Active Plugins (32) ###

WPML Multilingual CMS: por OnTheGoSystems – 4.5.8
Advanced Custom Fields: por Cerebros deliciosos – 5.12.2
Advanced Woo Search: por ILLID – 2.55
Akismet Anti-Spam: por Automattic – 4.2.4
Contact Form 7: por Takayuki Miyoshi – 5.5.6.1
Consentiment de galeta RGPD: por WebToffee – 2.1.2
Join.chat: por Creame – 4.5.1
Custom Fields for Gutenberg Block Editor: por Jeff Starr – 2.3.3
Duplicate Page: por mndpsingh287 – 4.4.8
Envialia for Woocommerce: por Envialia – 1.2.4
Facebook for WooCommerce: por Facebook – 2.6.15
Genesis Connect for WooCommerce: por StudioPress – 1.1.1
Smash Balloon Instagram Feed: por Smash Balloon – 6.0.5
WPBakery Page Builder: por Michael M - WPBakery.com – 6.9.0
Quipu for WooCommerce: por Shadi Manna – 1.0
Regenerate Thumbnails: por Alex Mills (Viper007Bond) – 3.1.5
Slider Revolution: por ThemePunch – 6.5.24
Templatera: por WPBakery – 1.1.12
UpdraftPlus - Backup/Restore: por UpdraftPlus.Com
DavidAnderson – 2.22.12.25

Woo Discount Rules: por Flycart – 2.4.1
WooCommerce Redsys Gateway Light: por José Conti – 3.0.6
Abandoned Cart Lite for WooCommerce: por Tyche Softwares – 5.12.0
WooCommerce Multilingual & Multicurrency: por OnTheGoSystems – 5.0.1
WooCommerce Quantity Increment: por Automattic
WooThemes – 1.1.0

WooCommerce: por Automattic – 6.5.1
Yoast SEO: por Equipo Yoast – 19.0
WP All Export Pro: por Soflyy – 1.7.6
WP Mail SMTP: por WPForms – 3.4.0
WP All Export - WooCommerce Export Add-On Pro: por Soflyy – 1.0.4
WPML Media: por OnTheGoSystems – 2.7.0
WPML String Translation: por OnTheGoSystems – 3.2.1
YITH WooCommerce Product Add-ons & Extra Options: por YITH – 2.10.0

### Inactive Plugins (4) ###

Font Awesome: por Font Awesome – 4.1.1
Holded integration: por Holded – 3.3.3
Packlink PRO Shipping: por Packlink Shipping S.L. – 3.2.9
WP Rocket: por WP Media – 3.9.1.1

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
outofstock (outofstock-es)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: ✔
Enforce Approved Product Download Directories: –

### WC Pages ###

Base de la tienda: ❌ Página sin definir
Carrito: #20316 - /cistella/
Finalizar compra: #20317 - /finalitza-la-compra/
Mi cuenta: #20318 - /el-meu-compte/
Términos y condiciones: #4861 - /politica-privacidad/

### Theme ###

Name: Tocs
Version: 2.3.0
Author URL: http://www.webmillennial.com
Child Theme: ✔
Parent Theme Name: Genesis
Parent Theme Version: 3.3.5
Parent Theme Author URL: https://www.studiopress.com/
WooCommerce Support: ✔

### Templates ###

Overrides: tocs/woocommerce/archive-product.php
tocs/woocommerce/checkout/form-billing.php
tocs/woocommerce/checkout/form-checkout.php
tocs/woocommerce/checkout/review-order.php
tocs/woocommerce/checkout/terms.php
tocs/woocommerce/content-product.php
tocs/woocommerce/single-product.php


### Action Scheduler ###

Completo: 7.061
Oldest: 2022-05-03 19:59:54 +0000
Newest: 2022-06-02 22:12:16 +0000

Fallida: 1
Oldest: –
Newest: –

Pendiente: 3
Oldest: 2022-06-02 22:22:06 +0000
Newest: 2022-06-03 15:52:24 +0000


### Status report information ###

Generated at: 2022-06-03 00:22:07 +02:00
`
```

**Comment by rawdreeg** [comment]
I am still not able to reproduce the issue. From your screenshot, I see you're using a number of plugins that could change the global $post variable. I suggest running a [conflict check ](https://woocommerce.com/document/how-to-test-for-conflicts/) on a staging site or if the issue still persists, please open a support ticket on woocommerce.com or the [wordpress.org forums](https://wordpress.org/support/plugin/facebook-for-woocommerce/) if you need further assistance.

**Comment by gendrith** [comment]
Well, when a deactivate your plugin, the error disappears, that's why I asked here...
