### ISSUE TITLE
Unable to setup plugin

### ISSUE THREAD

**Issue by TimMcCauley** [woocommerce/facebook-for-woocommerce#2304]
## 🔎 Isolate the bug

I haven't confirmed these yet. If anyone is aware of this bug and can suggest an older version to use, I would appreciate the hint.

- [ ] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [ ] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug

I have installed the most recent version of the plugin from the plugins manager and I am seeing a 500 network error. My wordpress version is  `WordPress 5.8.2` running via docker. WC version is `Version 5.9.1`. 

## 🚶‍♀️ Steps to reproduce

Install and activate the plugin. Click on "finish set up" -> 500, blank page.

## ✔️ Expected behavior

I would expect to be able to see the settings page.

## 🗃 Logs

<details>
An error of type E_ERROR was caused in line 370 of the file /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php. Error message: Uncaught Error: Call to undefined method DateTime::getOffsetTimestamp() in /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php:370
Stack trace:
#0 /var/www/html/wp-content/plugins/facebook-for-woocommerce/includes/fbproduct.php(609): WC_Facebook_Product->add_sale_price(Array)
#1 /var/www/html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(2040): WC_Facebook_Product->prepare_product()
#2 /var/www/html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(819): WC_Facebookcommerce_Integration->get_sample_product_feed()
#3 /var/www/html/wp-includes/class-wp-hook.php(303): WC_Facebookcommerce_Integration->load_assets('marketing_page_...')
#4 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#6 /var/www/html/wp-admin/admin-header.php(102): do_action('admin_enqueue_s...', 'marketing_page_...')
#7 /var/www/html/wp-admin/admin.php(239): require_once('/
</details>

**Comment by TimMcCauley** [comment]
Greetings @ibndawood thank you for your quick reply. Highly appreciated - it is the following:

```
`
### WordPress Environment ###

WordPress address (URL): http://boundlessmaps.com
Site address (URL): http://boundlessmaps.com
WC Version: 5.9.1
REST API Version: ✔ 5.9.1
WC Blocks Version: ✔ 6.1.0
Action Scheduler Version: ✔ 3.3.0
WC Admin Version: ✔ 2.8.0
Log Directory Writable: ✔
WP Version: ❌ 5.8.2 - There is a newer version of WordPress available (6.0.2)
WP Multisite: –
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache/2.4.51 (Debian)
PHP Version: 7.4.25
PHP Post Max Size: 8 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 8.0.27
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.9.1
WC Database Prefix: wp_
Total Database Size: 507.17MB
Database Data Size: 451.65MB
Database Index Size: 55.52MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 14.02MB + Index: 12.16MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 8.02MB + Index: 6.05MB + Engine InnoDB
wp_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_failed_logins: Data: 301.34MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_activity: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_login_lockdown: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_aiowps_permanent_block: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_cookies: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
wp_ewwwio_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_fbv_attachment_folder: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_options: Data: 7.05MB + Index: 1.20MB + Engine InnoDB
wp_postmeta: Data: 73.14MB + Index: 10.38MB + Engine InnoDB
wp_posts: Data: 14.08MB + Index: 6.13MB + Engine InnoDB
wp_term_relationships: Data: 1.52MB + Index: 1.52MB + Engine InnoDB
wp_term_taxonomy: Data: 0.39MB + Index: 0.39MB + Engine InnoDB
wp_termmeta: Data: 1.52MB + Index: 0.69MB + Engine InnoDB
wp_terms: Data: 0.36MB + Index: 0.50MB + Engine InnoDB
wp_usermeta: Data: 0.08MB + Index: 0.03MB + Engine InnoDB
wp_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 0.41MB + Index: 0.67MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_csv_uploads: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_logging: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_media: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_menus: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_project: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_page: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_project_table: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_publisher: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wpda_table_design: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpda_table_settings: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpforms_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.05MB + Index: 0.00MB + Engine InnoDB
wp_yoast_indexable: Data: 24.36MB + Index: 10.31MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 2.42MB + Index: 4.39MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_seo_links: Data: 0.02MB + Index: 0.03MB + Engine InnoDB

### Post Type Counts ###

accordions: 3
attachment: 20228
custom_css: 1
feedback: 13
filter-field: 1
filter-set: 1
jetpack_migration: 2
nav_menu_item: 27
oembed_cache: 1
page: 19
post: 2
product: 4242
revision: 331
shop_order: 60
shop_order_refund: 10
tablepress_table: 2
wpcf7_contact_form: 3

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (30) ###

Accordions by PickPlugins: by PickPlugins – 2.2.34
FiboSearch - AJAX Search for WooCommerce: by FiboSearch Team – 1.16.0
All In One WP Security: by Tips and Tricks HQ
Peter Petreski
Ruhul
Ivy – 4.4.9

Better Font Awesome: by Mickey Kay – 2.0.1
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 5.5.2
Contact Form 7 Image Captcha: by KC Computing – 3.2.4
Contact Form 7: by Takayuki Miyoshi – 5.5.2
Custom Upload Dir: by Ulf Benjaminsson – 3.4.6
Extensions for Leaflet Map: by hupe13 – 2.2.5
Instant Indexing: by Rank Math – 1.1.3
Filter Everything — WooCoomerce Product & WordPress Filter: by Andrii Stepasiuk – 1.4.4
Fly Dynamic Image Resizer: by Junaid Bhura – 2.0.8
Jetpack: by Automattic – 10.3
Leaflet Map: by bozdoz – 3.0.4
Pinterest for WooCommerce: by WooCommerce – 1.0.11 (update to version 1.2.2 is available)
Scripts n Styles: by unFocus Projects – 3.5.1
Simple Image Sizes: by Rahe – 3.2.1
Simple-JWT-Login: by Nicu Micle – 3.3.1
TablePress: by Tobias Bäthge – 1.14
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.5.0
WooCommerce Stripe Gateway: by WooCommerce – 5.7.0
WooCommerce Payments: by Automattic – 3.2.3 (update to version 4.7.2 is available)
WooCommerce PayPal Payments: by WooCommerce – 1.6.1 (update to version 1.9.3 is available)
WooCommerce PDF Invoices & Packing Slips: by Ewout Fernhout – 2.10.3
WooCommerce Shipping & Tax: by WooCommerce – 1.25.19 (update to version 1.26.3 is available)
WooCommerce: by Automattic – 5.9.1 (update to version 6.9.3 is available)
Yoast SEO: by Team Yoast – 17.7.1
WP Mail SMTP: by WPForms – 3.2.0
Wp Maximum Upload File Size: by CodePopular – 1.0.6
WP Super Cache: by Automattic – 1.7.4

### Inactive Plugins (4) ###

CTX Feed: by WebAppick – 4.4.59
Facebook for WooCommerce: by Facebook – 2.6.23
WordPress REST API Authentication: by miniOrange – 2.4.0
WP Data Access: by Passionate Programmers B.V. – 5.1.2

### Dropin Plugins (1) ###

advanced-cache.php: advanced-cache.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: ❌ Page visibility should be public
Cart: #368 - /cart/
Checkout: #369 - /checkout/
My account: #370 - /my-account/
Terms and conditions: #1321 - /terms/

### Theme ###

Name: Frame
Version: 1.0.1
Author URL: https://fuelthemes.net
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Overrides: frame/woocommerce/content-widget-product.php

### WooCommerce PayPal Payments ###

Onboarded: Yes
Shop country code: DE
PayPal card processing available in country: No
Pay Later messaging available in country: Yes
Vault enabled: Yes

### Action Scheduler ###

Canceled: 2
Oldest: 2022-09-09 14:54:25 +0000
Newest: 2022-09-25 12:10:44 +0000

Complete: 30,996
Oldest: 2022-08-27 16:50:03 +0000
Newest: 2022-09-26 10:52:31 +0000

Failed: 227
Oldest: 2022-04-25 08:39:24 +0000
Newest: 2022-09-24 07:32:51 +0000

Pending: 3
Oldest: 2022-09-26 11:02:31 +0000
Newest: 2022-09-26 13:16:51 +0000


### Status report information ###

Generated at: 2022-09-26 11:01:49 +00:00
```

**Comment by TimMcCauley** [comment]
Thanks @ibndawood
