### ISSUE TITLE
Facebook Plugin Causing Critical Errors in Wordpress

### ISSUE THREAD

**Issue by HalvorsenInteriors** [woocommerce/facebook-for-woocommerce#2321]
## 🔎 Isolate the bug

- [X] I have confirmed this occurs in the most recent version of WordPress, WooCommerce, and Facebook for WooCommerce.
- [X] I have confirmed this occurs when only WooCommerce and Facebook for WooCommerce are active and when using a default WordPress or WooCommerce theme.

## ✍️ Describe the bug
<Latest version causes the WooCommerce settings page to throw a fatal error. Once I hit the UPDATE button in the Product Pages it send to a error page stating the following - "There has been a critical error on this website. Please check your site admin email inbox for instructions". Also on the product page the following error message shows - "Facebook Product Sync
There has been a critical error on this website. Please check your site admin email inbox for instructions". I have disabled the plugin until further notice from the plugin developer>

## 🚶‍♀️ Steps to reproduce
<Disable plugin for the time being until the plugin has been fixed>

## ✔️ Expected behavior
<Amendments to the product pages should be able to be updated properly. -->

## 🗃 Logs
<N/a>

<details>
	
</details>

**Comment by Mikroo32** [comment]
I have just had exactly the same issue as described. After hitting UPDATE button. The following critical error-

Fatal error: Uncaught Error: Call to a member function update_product_group() on null in /home/customer/www/thelasercutshop.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php:1495 Stack trace: #0 /home/customer/www/thelasercutshop.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(1238): WC_Facebookcommerce_Integration->update_product_group(Object(WC_Facebook_Product)) #1 /home/customer/www/thelasercutshop.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php(949): WC_Facebookcommerce_Integration->on_variable_product_publish(6748) #2 /home/customer/www/thelasercutshop.com.au/public_html/wp-includes/class-wp-hook.php(309): WC_Facebookcommerce_Integration->on_product_save(6748) #3 /home/customer/www/thelasercutshop.com.au/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #4 /home/customer/www/thelasercutshop.com.au/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /home/cus in /home/customer/www/thelasercutshop.com.au/public_html/wp-content/plugins/facebook-for-woocommerce/facebook-commerce.php on line 1495
There has been a critical error on this website. Please check your site admin email inbox for instructions.
[Learn more about troubleshooting WordPress.](https://wordpress.org/support/article/faq-troubleshooting/)

**Comment by rawdreeg** [comment]
Thanks for reporting. We've made some changes to our class autoloader that seemed to result in the issue. We're preparing a release that will fix the issue. We will update you as soon as we have published the release.

This will be fixed #2324

**Comment by rawdreeg** [comment]
A new update of the plugin has been released. Plugin update the Facebook for WooCommerce plugin version 2.6.27 to fix the issue

**Comment by HalvorsenInteriors** [comment]
FYI The latest version I have installed is the Version 2.6.27, which i am having issues with.  Should I delete and reinstall?
