### ISSUE TITLE
Fatal error after bug-fix in WC Blocks

### ISSUE THREAD

**Issue by ahegyes** [woocommerce/facebook-for-woocommerce#2489]
## ✍️ Describe the bug

Version 9.7.0 of WC Blocks fixed a bug that initialized the WC Cart on admin requests (e.g., in the Gutenberg editor). Consequently, the WC Cart global is now `null` by default in the Gutenberg editor as WC Core intended it to be.

On the editor's `enqueue_block_editor_assets` action, all WC blocks enqueue their `enqueue_editor_assets` method which simply calls their `enqueue_data` method ([source](https://github.com/woocommerce/woocommerce-blocks/blob/2d7434a9a4f83a5f8f37e6080f0c6328b467db49/src/BlockTypes/AbstractBlock.php#L96-L101)).

In the case of the WC Checkout block, the `enqueue_data` method ends with a call for the action `woocommerce_blocks_checkout_enqueue_data` ([source](https://github.com/woocommerce/woocommerce-blocks/blob/2d7434a9a4f83a5f8f37e6080f0c6328b467db49/src/BlockTypes/Checkout.php#L349)).

On the `woocommerce_blocks_checkout_enqueue_data` action, Facebook for WooCommerce enqueued its `WC_Facebookcommerce_EventsTracker::inject_initiate_checkout_event` method ([source](https://github.com/woocommerce/facebook-for-woocommerce/blob/9edba367aaf3ae408a6c0c723a1ca81ae3112c90/facebook-commerce-events-tracker.php#L127)).

The `inject_initiate_checkout_event` method accesses methods on the `WC()->cart` variable which is now `null` in the editor. This causes a fatal PHP error that causes the editor to crash ([source](https://github.com/woocommerce/facebook-for-woocommerce/blob/9edba367aaf3ae408a6c0c723a1ca81ae3112c90/facebook-commerce-events-tracker.php#L820)). 

The reason why I'm claiming that this is a bug in Facebook for WooCommerce is that WooCommerce Core only loads the cart on front-end requests ([source](https://github.com/woocommerce/woocommerce/blob/1834621d1a5870ffad62daa955bd1c95da6f353c/plugins/woocommerce/includes/class-woocommerce.php#L665-L667)). The fact that the cart variable was non-null in the editor before WC Blocks 9.7.0 must've therefore been a bug that was now fixed. When the next release of WooCommerce comes out and WC Blocks 9.7 is merged, Facebook for WooCommerce will start throwing this error on all sites that update.

## 🚶‍♀️ Steps to reproduce

1. Install WooCommerce (latest), WooCommerce Blocks (9.7.0+), and Facebook for WooCommerce (latest)
1. Enable the Facebook Pixel tracking
1. Try to edit any post type that uses the Gutenberg editor (post, page, or custom)
1. A fatal PHP error will occur

## ✔️ Expected behavior
That the Gutenberg editor loads and that no error shows up. If I add a check for `is_null( WC()->cart )` or simply comment out the line `add_action( 'woocommerce_blocks_checkout_enqueue_data', array( $this, 'inject_initiate_checkout_event' ) );`, the error does go away. 

A good fix for this would therefore be to [change this line](https://github.com/woocommerce/facebook-for-woocommerce/blob/9edba367aaf3ae408a6c0c723a1ca81ae3112c90/facebook-commerce-events-tracker.php#L820) to this (notice the extra check for null):

`if ( ! $this->is_pixel_enabled() || is_null( WC()->cart ) || WC()->cart->get_cart_contents_count() === 0 || $this->pixel->is_last_event( 'InitiateCheckout' ) ) {`

## 🗃 Logs
Here's the stack trace of the error:

```
WordPress version 6.1.1
Current plugin: Facebook for WooCommerce (version 3.0.13)
PHP version 7.4.33

Error Details
=============
An error of type E_ERROR was caused in line 820 of the file
/srv/htdocs/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php.
Error message: Uncaught Error: Call to a member function
get_cart_contents_count() on null in
/srv/htdocs/wp-content/plugins/facebook-for-woocommerce/facebook-commerce-events-tracker.php:820
Stack trace:
#0 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308):
WC_Facebookcommerce_EventsTracker->inject_initiate_checkout_event('')
#1 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332):
WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /srv/htdocs/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/Checkout.php(349):
do_action('woocommerce_blo...')
#4 /srv/htdocs/wp-content/plugins/woo-gutenberg-products-block/src/BlockTypes/AbstractBlock.php(100):
Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data()
#5 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(308):
Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_editor_assets('')
#6 /wordpress/core/6.1.1/wp-includes/class-wp-hook.php(332):
WP_Hook->apply_filters(NULL, Array)
#7 /wordpress/core/6.1.1/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#8 /wordpress/core/6.1.1/wp-admin/edit-form-blocks.php(272):
do_action('enqueue_block_e...')
#9 /wordpress/core/6.1.1/wp-admin/post.php(187): require('/wordpress/core...')
#10 {main}
thrown
```

**Comment by zdenys** [comment]
Encountered in 40729627-hc

**Comment by zdenys** [comment]
41188472-hc (6008400-zd-woothemes)

**Comment by tomxygen** [comment]
I can reproduce the issue. 
I fixed by removing WC Blocks. 

> When the next release of WooCommerce comes out and WC Blocks 9.7 is merged, Facebook for WooCommerce will start throwing this error on all sites that update

I hope this doesn't happen, otherwise thousands of stores will have this issue.

**Comment by jp-imagines** [comment]
Also encountered in 35280752-hc (6006243-zd-woothemes). WooCommerce Blocks has been deactivated on this site as a workaround for now.

**Comment by deancroyal** [comment]
Ran into this here 39490742-hc. When attempting to edit any post, after several seconds of blank screen, an error prompt would appear: "There has been a critical error on this website...".

I have deactivated WooCommerce Blocks plugin to resolve issue for now.

**Comment by sukafia** [comment]
Thank you!

**Comment by dev-sabbir** [comment]
6009695-zd-woothemes
